### ISSUE TITLE
Question about KeyError: 'radar_data'

### ISSUE THREAD

**Issue by lcy0308** [Zhuanglong2/T-RODNet#9]
Hi, thank you very much for your work. I recently got an error while training a network and I would like your help. The errors are as follows: 
1. When I was training, it reported an error 
  ```
Traceback (most recent call last):
  File "train.py", line 242, in <module>
    data = data_dict['radar_data']
KeyError: 'radar_data'
```
2. When switching to save_memory mode, many errors
 ```
Process Process-1 occurs:
Traceback (most recent call last):
  File "/usr/local/miniconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self. run()
  File "/usr/local/miniconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/hy-tmp/T-RODNet-main/rodnet/datasets/CRDataLoader.py", line 129, in getBatchArray
    shradarnp[index, :len(loading_seq), :, :, :, :] = data_dict['radar_data']
KeyError: 'radar_data'
Traceback (most recent call last):
  File "train.py", line 240, in <module>
    for iter, data_dict in enumerate(dataloader):
  File "/hy-tmp/T-RODNet-main/rodnet/datasets/CRDataLoader.py", line 99, in __iter__
    obj_infos=data_dict_stack[index_num]['anno']['obj_infos'],
KeyError: 'anno'
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self. run()
  File "/usr/local/miniconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/hy-tmp/T-RODNet-main/rodnet/datasets/CRDataLoader.py", line 129, in getBatchArray
    shradarnp[index, :len(loading_seq), :, :, :, :] = data_dict['radar_data']
KeyError: 'radar_data'
```
It seems that these problems are all related to data_dict['radar_data'], I have converted the data into pickl format according to the readme file, and hope to get your help as soon as possible.

**Comment by prodseu** [comment]
Hi, 
Did you remove those data of CRUW after using 'prepare_data.py'? I've met the same question and found that you should not remove those original data. Then it will work smoothly. Hope it's helpful.

**Comment by Zhuanglong2** [comment]
We have resolved the issue where T-RODNet training fails on some graphics cards. Please download our latest project for training.

**Comment by XiyuanFan** [comment]
Traceback (most recent call last):
  File "tools/train.py", line 201, in <module>
    data = data_dict['radar_data']
KeyError: 'radar_data
一直报这个错误是什么原因？
